services:
  frontend:
    container_name: dushanbesoft_landing
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3121:3121"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PORT=3121
    networks:
      - dushanbesoft_landing_app_network

networks:
  dushanbesoft_landing_app_network:
    driver: bridge
