import type { Metadata } from "next";
import "../../styles/globals.css";
import { dir } from 'i18next';
import { i18nConfig } from "../../../i18nConfig";
import { ReactNode } from "react";
import { tektur, nunitoSans } from "../../styles/fonts";

export const metadata: Metadata = {
  title: "Dushanbe soft",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/site-favicon.svg",
  },
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params
}: {
  children: ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  
  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={`${tektur.variable} ${nunitoSans.variable}`}>{children}</body>
    </html>
  );
}
